<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" style="height:400px;" width=500/></p>

<h3 style="text-align: center;"><b>Бакалаврськая студія Штучний Інтелект, Київська школа економіка(KSE)</b></h3>

***Ми можемо писати наступний код.***

In [7]:
%%time
arr = []
n = 10**7
for i in range(n):
    arr.append(i*5)

CPU times: user 655 ms, sys: 71.7 ms, total: 727 ms
Wall time: 734 ms


***Або такий...***

In [8]:
%%time
def summ(a):
    ans = 0
    for i in a:
        ans += i
    return ans

arr = range(10**7)

print(summ(arr))

49999995000000
CPU times: user 303 ms, sys: 20.5 ms, total: 324 ms
Wall time: 325 ms


# Numpy library.
- ***``Numpy`` - це бібліотека Python для обраховувально-ефективних операцій з багатовимірними масивами***


- ***Пакет ``Numpy`` дає можливість використовувати $n$-вимірні однорідні масиви, в них не можна вставити або видалити елмент в будь-якому місці. У ``Numpy`` - лінійна алгебра для пайтон.***

In [9]:
!which python

/Users/alexeyomelchenko/anaconda3/bin/python


In [10]:
# !conda install numpy
# !pip3 install numpy

In [11]:
import numpy as np

## 1. Одновимірні масиви

In [12]:
a = [1, 2, 3]
b = np.array(a, dtype='float64')
print(type(b), type(a))

<class 'numpy.ndarray'> <class 'list'>


***Якщо типи різн, то йде неявний каст до одного з типів.***

In [13]:
a = [1, 2, 'a']
b = np.array(a)
print("Для list:", type(a[0]),
      "\nДля np.array:", type(b[0]))

Для list: <class 'int'> 
Для np.array: <class 'numpy.str_'>


In [14]:
d = np.array([1, 2, 3])
d

array([1, 2, 3])

In [15]:
type(d)

numpy.ndarray

***Можемо подивитись на всі методи класу ``ndarray``.***

In [16]:
set(dir(b)) - set(dir(object))

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delitem__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__float__',
 '__floordiv__',
 '__getitem__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__len__',
 '__lshift__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__neg__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',

***Наприклад можемо дізнатись розмір масиву.***

In [17]:
arr = np.array([5, 6, 2, 1, 10], dtype='int32')

In [18]:
arr.nbytes

20

In [19]:
import numpy as np

***Якщо ви не знаєте потрібну функцую, але знайєте про що вона, то може знайти інформацію в документації numpy або використати метод ``lookfor``.***

In [20]:
np.lookfor('max value of array') 

Search results for 'max value of array'
---------------------------------------
numpy.ma.argmax
    Returns array of indices of the maximum values along the given axis.
numpy.ma.MaskedArray.argmax
    Returns array of indices of the maximum values along the given axis.
numpy.fmax
    Element-wise maximum of array elements.
numpy.argmax
    Returns the indices of the maximum values along an axis.
numpy.nanmax
    Return the maximum of an array or maximum along an axis, ignoring any
numpy.maximum
    Element-wise maximum of array elements.
numpy.nanargmax
    Return the indices of the maximum values in the specified axis ignoring
numpy.ptp
    Range of values (maximum - minimum) along an axis.
numpy.bincount
    Count number of occurrences of each value in array of non-negative ints.
numpy.ma.maximum
    Element-wise maximum of array elements.
numpy.chararray.clip
    Return an array whose values are limited to ``[min, max]``.
numpy.matrix.argmax
    Indexes of the maximum values along a

In [6]:
np.con*?

np.concatenate
np.conj
np.conjugate
np.convolve

In [21]:
?np.ma.mean

Signature:       np.ma.mean(a, *args, **params)
Type:            _frommethod
String form:     <numpy.ma.core._frommethod object at 0x15ab65ff0>
File:            /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/ma/core.py
Docstring:      
mean(self, axis=None, dtype=None, out=None, keepdims=<no value>)

Returns the average of the array elements along given axis.

Masked entries are ignored, and result elements which are not
finite will be masked.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.ndarray.mean : corresponding function for ndarrays
numpy.mean : Equivalent function
numpy.ma.average : Weighted average.

Examples
--------
>>> a = np.ma.array([1,2,3], mask=[False, False, True])
>>> a
masked_array(data=[1, 2, --],
             mask=[False, False,  True],
       fill_value=999999)
>>> a.mean()
1.5
Class docstring:
Define functions from existing MaskedArray methods.

Parameters
----------
methodname : str
    Name of the 

***Глянемо на кількісні характеристики ``ndarray``.***

In [ ]:
arr = np.array([[[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]], 
                [[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]]])
print(arr)

[[[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]

 [[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]]


In [ ]:
print("len:", len(arr), "-- кі-ть елментів по першій вісі.",
      "\nsize:", arr.size, "-- всього елментів у матриці.",
      "\nndim:", arr.ndim, "-- розмір матриці.",
      "\nshape:", arr.shape, "-- кі-ть елментів по кожній осі.")

len: 2 -- количество элементов по первой оси. 
size: 24 -- всего элементов в матрице. 
ndim: 3 -- размерность матрицы. 
shape: (2, 3, 4) -- количество элементов по каждой оси.


***Індекси.***

In [ ]:
a = np.array([1, 2, 3, 4])
a[0], a[1]

(1, 2)

***Останній елемент.***

In [ ]:
a[-1]

4

***Можемо змінювати об'єкти масиву.***

In [ ]:
a[2] = -1
a

array([ 1,  2, -1,  4])

***``ndarray`` можна, але не треба використовувати в циклах, бо ви втрачаємо основу фішку `Numpy` -- швидкість. За можливості завжди використовувати операції над масивами, як єдине ціле.***

In [ ]:
for i in a:
    print(i)

1
2
-1
4


**Task 1:** Створити numpy-масив, який складається з перших 4 цифр множини цілих невід'ємних чисел, виведіть його тип и розмір:

In [ ]:
# решение

arr = np.array([2, 3, 5, 7])
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.shape)
print(arr.nbytes)

[2 3 5 7]
int64
<class 'numpy.ndarray'>
(4,)
32


## Створення масивів.

In [ ]:
a = np.zeros(7) # масив з нулів
b = np.ones(7, dtype=np.int16) # масив з одиниць
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1]


***Часто треба створювати нулевий масив, такий самий як інший.***

In [ ]:
c = np.zeros(7)
c

array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
c = np.zeros_like(b)
c

array([0, 0, 0, 0, 0, 0, 0], dtype=int16)

***Функція `np.arange` схожа до `range`. Аргуенти можуть бути з не цілими числами. Треба запобігати ситуації, коли (кінець-початок) / шаг - ціле число, бо в цьому випадку включення останнього елменту залежить від помилки округлення. Краще, щоб кінець діапазонк був десь посередині кроку.***

In [ ]:
a = np.arange(1, 16, 4)
b = np.arange(5., 21, 2)
c = np.arange(1, 10)
d = np.arange(5)
print(a)
print(b)
print(c)
print(d)

[ 1  5  9 13]
[ 5.  7.  9. 11. 13. 15. 17. 19.]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


***Послідонвість чисел з постійним кроком можливо також створювати функцією `linspace`. Початок і кінець діапазону включається; останній аргумент -- число крапок.***

In [ ]:
a = np.linspace(1, 15, 2)
b = np.linspace(5, 12, 10)
print(a)
print(b)

[ 1. 15.]
[ 5.          5.77777778  6.55555556  7.33333333  8.11111111  8.88888889
  9.66666667 10.44444444 11.22222222 12.        ]


**Задача 2:** Створити і вивести послідовність чисел від  10 до 32 з постійним кроком, довжина послідовності - 12, Чом дорівнює крок?

In [ ]:
# solution

a = np.linspace(10, 32, 12)
print(a)
print(a[1] - a[0])



[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
2.0


# 2. Операції на одновимірних масивах.

***Всі арифметичні операції відбуваються поелментно.***

In [ ]:
print(a)
print(b)

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]


In [ ]:
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 11)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
[  -6.  -24.  -54.  -96. -150. -216. -294. -384. -486. -600. -726.]
[-1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5]


***Один з операндів може бути скаляром, а не масивом.***

In [ ]:
print(5*a)
print(10 + b)

[ 15.  30.  45.  60.  75.  90. 105. 120. 135. 150. 165.]
[  8.   6.   4.   2.   0.  -2.  -4.  -6.  -8. -10. -12.]


In [ ]:
print((a + b) ** 2)
print(2 ** (a + b))

[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01 6.400e+01 1.280e+02
 2.560e+02 5.120e+02 1.024e+03 2.048e+03]


***Якщо типи елментів різні, то йже каст до більшого.***

In [ ]:
print(a + np.arange(11, dtype='int16'))
print(type(a[0]))

[ 3.  7. 11. 15. 19. 23. 27. 31. 35. 39. 43.]
<class 'numpy.float64'>


***У ``Numpy`` є елементарні функції, які теж застосовуються до масивів поелментно.Вони називаються універсальними функціями (``ufunc``).***

In [ ]:
type(np.cos)

numpy.ufunc

In [ ]:
np.cos(a)

array([-0.9899925 ,  0.96017029, -0.91113026,  0.84385396, -0.75968791,
        0.66031671, -0.54772926,  0.42417901, -0.29213881,  0.15425145,
       -0.01327675])

In [ ]:
np.log(b)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

***Логічні операції також відбуваються поелементно.***

In [ ]:
print(a > b)
print(a == b)
print(a >= 10)

[ True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False]
[False False False  True  True  True  True  True  True  True  True]


***Квантори ``загальності`` та ``існування``.***
$$\forall$$
$$\exists$$

In [ ]:
c = np.arange(0., 20)
print(type(c[0]))

<class 'numpy.float64'>


In [ ]:
np.any(c == 0.), np.all(c)

(True, False)

***Inplace операції.***

In [ ]:
c += np.sin(4)
print(c)

[-0.7568025  0.2431975  1.2431975  2.2431975  3.2431975  4.2431975
  5.2431975  6.2431975  7.2431975  8.2431975  9.2431975 10.2431975
 11.2431975 12.2431975 13.2431975 14.2431975 15.2431975 16.2431975
 17.2431975 18.2431975]


***Inplace оп можливі тільки для операндів однакового типу.***

In [ ]:
c *= 2
print(c)

[-1.51360499  0.48639501  2.48639501  4.48639501  6.48639501  8.48639501
 10.48639501 12.48639501 14.48639501 16.48639501 18.48639501 20.48639501
 22.48639501 24.48639501 26.48639501 28.48639501 30.48639501 32.48639501
 34.48639501 36.48639501]


In [ ]:
b = np.arange(1., 21, 1)

d = (b + c)
d /= b
print(d)

[-0.51360499  1.2431975   1.82879834  2.12159875  2.297279    2.41439917
  2.49805643  2.56079938  2.60959945  2.6486395   2.68058136  2.70719958
  2.72972269  2.74902821  2.76575967  2.78039969  2.79331735  2.80479972
  2.81507342  2.82431975]


***При діленні ``ndarray`` на нулі, виключенн не викидується.***

In [ ]:
print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))

[  0.  nan  inf -inf]


***Константи.***

In [ ]:
print(np.e, np.pi)

2.718281828459045 3.141592653589793


In [ ]:
print(b)
print(b.cumsum())

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[  1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91. 105.
 120. 136. 153. 171. 190. 210.]


***Подивимось на сортування numpy-масивів.***

In [ ]:
a = np.array([1, 5, 6, 10, -2, 0, 18])

In [ ]:
print(np.sort(a))
print(a)

[-2  0  1  5  6 10 18]
[ 1  5  6 10 -2  0 18]


***Тепер використаємо, як метод.***

In [ ]:
a.sort()
print(a)

[-2  0  1  5  6 10 18]


In [ ]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

***Об'єднуємо масиви.***

In [ ]:
c = np.hstack((a, b, 5*b))
c

array([-2.,  0.,  1.,  5.,  6., 10., 18.,  1.,  1.,  1.,  1.,  1.,  5.,
        5.,  5.,  5.,  5.])

***Розділяємо масив.***

In [ ]:
x1, x2, x3, x4 = np.hsplit(a, [3, 5, 6])
print(a)
print(x1)
print(x2)
print(x3)
print(x4)

[-2  0  1  5  6 10 18]
[-2  0  1]
[5 6]
[10]
[18]


***функції ``append`` ``delete`` ``insert`` не Inplace функції.***

In [ ]:
print(np.delete(a, [2, 4, 1]))
print(a)

[-2  5 10 18]
[-2  0  1  5  6 10 18]


In [ ]:
np.insert(a, 2, [-1, -1])

array([-2,  0, -1, -1,  1,  5,  6, 10, 18])

In [ ]:
np.append(a, [2.2, 2.1])

array([-2. ,  0. ,  1. ,  5. ,  6. , 10. , 18. ,  2.2,  2.1])

## Індексація масивів і зрізи.

***Масив у зворотньому порядку.***

In [ ]:
a[::-1]

array([18, 10,  6,  5,  1,  0, -2])

***Діапазон індексів. Створюється новий заголовок масиву, який вказує на ті самі дані. Зміни, зроблені через такий самий масив, буде видно і в початкову масиві.***

In [ ]:
print(a)

[-2  0  1  5  6 10 18]


In [ ]:
a[2:5]

array([1, 5, 6])

In [ ]:
b = a[0:6] # копія не створюється
b[1] = -1000
print(a)

[   -2 -1000     1     5     6    10    18]


***Діапазони з кроками.***

In [ ]:
b = a[0:4:2]
print(b)

# підмасиву можна присвоїти скаляр
a[1:6:3] = 0
print(a)

[-2  1]
[-2  0  1  5  0 10 18]


***Щоб скопіювати дані масиву, треба використати метод ``copy``.***

In [ ]:
b = a.copy()
b[2] = -4
print(b)
print(a)

[-2  0 -4  5  0 10 18]
[-2  0  1  5  0 10 18]


In [ ]:
print(a[[5,3,1]]) # масив індексів

[10  5  0]


**Завдання 3:**  
- Створити масив чисел від $-4\pi$  до $4\pi $, кі-ть точок 100
- порахувати суму поелментних квадратів синуса і косинуса для даного масиву.  
- За допомогою ``np.all`` перевірити, що всі елменти дорівюють одному.

In [ ]:
# вирішення

x = np.linspace(-4*np.pi, 4*np.pi, 100)

np.all((np.sin(x)**2 + np.cos(x)**2).round() == 1)

True

# 3. Двувимірні масиви

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
a.ndim, a.shape, len(a), a.size

(2, (2, 2), 2, 4)

***Звернення по індексу.***

In [ ]:
a[1][1], a[1,1]

(4, 4)

***Атрибуту ``shape`` можна присвоїти нове значення -- кортеж розмірів по всім координатам. Вийде новий заголовок масиву, його дані не зміняться.***

In [ ]:
b = np.arange(0, 20)
b.shape = (2, 10)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [ ]:
print(b.ravel()) # зтягування в одновимірний масив.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
a = np.ones((3, 3)) # подати tuple
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
b = np.zeros((3, 4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
d = np.diag(np.array([1, 2, 3, 4]))
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


***Завдання 4:***
Створити квадратну матрицю розміру 8, а на головній діагоналі має бути арифметична прогресія з кроком 3, починаючи з 3-ох, а на додатковій матриці -1, інші елементи 0

In [ ]:
# решение

a = -1*np.eye(8)[::-1] + np.diag(np.arange(3, 27, 3))
print(a)


[[ 3.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  6.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  9.  0.  0. -1.  0.  0.]
 [ 0.  0.  0. 12. -1.  0.  0.  0.]
 [ 0.  0.  0. -1. 15.  0.  0.  0.]
 [ 0.  0. -1.  0.  0. 18.  0.  0.]
 [ 0. -1.  0.  0.  0.  0. 21.  0.]
 [-1.  0.  0.  0.  0.  0.  0. 24.]]


***Множення матриць.***

In [ ]:
a = 5*np.ones((5, 5))
b = np.eye(5) + 1
print(a, '\n')
print(b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] 

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [ ]:
print(a*b, '\n') # поелементне множення
print(a @ b, '\n') # матричне множення
print(a.dot(b)) 

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


***Двовимірні масиви, які залежать тільки від одного індексу: $x_{ij}=u_j$, $y_{ij}=v_i$***

In [ ]:
u = np.linspace(1, 2, 2)
v = np.linspace(4, 8, 3)
print(u)
print(v)

[1. 2.]
[4. 6. 8.]


In [ ]:
x, y = np.meshgrid(u, v)
print(x, '\n')
print(y)

[[1. 2.]
 [1. 2.]
 [1. 2.]] 

[[4. 4.]
 [6. 6.]
 [8. 8.]]


# 4. Тензори (багатовимірні масиви)

In [ ]:
X = np.arange(64).reshape(8, 2, 4)
print(X)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]]

 [[56 57 58 59]
  [60 61 62 63]]]


In [ ]:
X.shape, len(X), X.size, X.ndim

((8, 2, 4), 8, 64, 3)

**Подивимось на сумі по різним вісям.***

In [ ]:
print(np.sum(X, axis=0), '\n')
print(np.sum(X, axis=1), '\n')
print(np.sum(X, axis=2), '\n')

# сумує одразу по обох вісях, тобто для фіксованої i 
# cумує тільки елементи з індексами (i, *, *)
print(np.sum(X, axis=(1, 2)))

[[224 232 240 248]
 [256 264 272 280]] 

[[  4   6   8  10]
 [ 20  22  24  26]
 [ 36  38  40  42]
 [ 52  54  56  58]
 [ 68  70  72  74]
 [ 84  86  88  90]
 [100 102 104 106]
 [116 118 120 122]] 

[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]
 [134 150]
 [166 182]
 [198 214]
 [230 246]] 

[ 28  92 156 220 284 348 412 476]


# 5. Лінійна алгебра

In [ ]:
a = np.array([[2, 1], [2, 3]])
print(a)

[[2 1]
 [2 3]]


***Визначник.***

In [ ]:
np.linalg.det(a)

4.0

***Знаходження оберненої.***

In [ ]:
b = np.linalg.inv(a)
print(b)

[[ 0.75 -0.25]
 [-0.5   0.5 ]]


In [ ]:
print(a.dot(b))
print(b.dot(a))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [ ]:
c = np.array([[2, 1], [6, 3]])
print(c)
print(np.linalg.det(c))

[[2 1]
 [6 3]]
0.0


# Корисні посилання



[GitHub NumPy](https://github.com/numpy/numpy)

[документація по NumPy](https://numpy.org/doc/stable/)